name: Python test
on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: true
        default: '3.13.2'
  push:

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '${{ github.event.inputs.python_version }}'

      - name: Install dependencies and Run tests
        run: |
          chmod +x -R ${{ github.workspace }}
          pip install --upgrade pip
          pip install -r requirements.txt
          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}
          pytest -s tests/part_01/test_users.py --junitxml=results.xml --html=report.html

      - name: Create test summary
        uses: test-summary/action@dist
        if: always()
        with:
          pathS: results.xml

      - name: Upload pytest results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results.xml
            report.html
            assets
      
      - name: Notify Slack - Build Status
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_MESSAGE: |
            ${{ job.status == 'success' && '✅ Python Tests completed successfully' || '❌ Python Tests failed' }} 
            on branch *${{ github.ref_name }}* by *${{ github.actor }}*.
            Details: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View on GitHub>
          SLACK_TITLE: "Build Status: ${{ job.status }}"

      - name: Send Build Status Email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "${{ job.status == 'success' && '✅ Build Succeeded' || '❌ Build Failed' }} - ${{ github.repository }}"
          html_body: >
            <!DOCTYPE html><html><body>
            <h2>${{ job.status == 'success' && '✅ Build Succeeded' || '❌ Build Failed' }}</h2>
            <p>Repository: <b>${{ github.repository }}</b></p>
            <p>Commit: <b>${{ github.sha }}</b></p>
            <p>Branch: <b>${{ github.ref_name }}</b></p>
            <p>Check the details on <a href="${{ github.server_url }}/actions">GitHub Actions</a>.</p>
            </body></html>
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}